// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIcecreamParams creates a new GetIcecreamParams object
// with the default values initialized.
func NewGetIcecreamParams() *GetIcecreamParams {
	var ()
	return &GetIcecreamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIcecreamParamsWithTimeout creates a new GetIcecreamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIcecreamParamsWithTimeout(timeout time.Duration) *GetIcecreamParams {
	var ()
	return &GetIcecreamParams{

		timeout: timeout,
	}
}

// NewGetIcecreamParamsWithContext creates a new GetIcecreamParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIcecreamParamsWithContext(ctx context.Context) *GetIcecreamParams {
	var ()
	return &GetIcecreamParams{

		Context: ctx,
	}
}

// NewGetIcecreamParamsWithHTTPClient creates a new GetIcecreamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIcecreamParamsWithHTTPClient(client *http.Client) *GetIcecreamParams {
	var ()
	return &GetIcecreamParams{
		HTTPClient: client,
	}
}

/*GetIcecreamParams contains all the parameters to send to the API endpoint
for the get icecream operation typically these are written to a http.Request
*/
type GetIcecreamParams struct {

	/*Name
	  name of icecream

	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get icecream params
func (o *GetIcecreamParams) WithTimeout(timeout time.Duration) *GetIcecreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get icecream params
func (o *GetIcecreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get icecream params
func (o *GetIcecreamParams) WithContext(ctx context.Context) *GetIcecreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get icecream params
func (o *GetIcecreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get icecream params
func (o *GetIcecreamParams) WithHTTPClient(client *http.Client) *GetIcecreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get icecream params
func (o *GetIcecreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get icecream params
func (o *GetIcecreamParams) WithName(name *string) *GetIcecreamParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get icecream params
func (o *GetIcecreamParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetIcecreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
