// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IcecreamClientRequest SaveOrUpdate icecream Request
// swagger:model IcecreamClientRequest
type IcecreamClientRequest struct {

	// allergy info
	AllergyInfo string `json:"allergy_info,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// dietary certifications
	DietaryCertifications string `json:"dietary_certifications,omitempty"`

	// an icecream request
	// in: body
	ID int64 `json:"id,omitempty"`

	// image closed
	ImageClosed string `json:"image_closed,omitempty"`

	// image open
	ImageOpen string `json:"image_open,omitempty"`

	// ingredients
	Ingredients []string `json:"ingredients"`

	// is deleted
	IsDeleted bool `json:"is_Deleted,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// product Id
	ProductID string `json:"product_id,omitempty"`

	// sourcing values
	SourcingValues []string `json:"sourcing_values"`

	// story
	Story string `json:"story,omitempty"`
}

// Validate validates this icecream client request
func (m *IcecreamClientRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IcecreamClientRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IcecreamClientRequest) UnmarshalBinary(b []byte) error {
	var res IcecreamClientRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
