// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IcecreamDelete Delete icecream Request
// swagger:model IcecreamDelete
type IcecreamDelete struct {

	// a icecream delete request
	// in: body
	ProductID string `json:"ProductId,omitempty"`
}

// Validate validates this icecream delete
func (m *IcecreamDelete) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IcecreamDelete) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IcecreamDelete) UnmarshalBinary(b []byte) error {
	var res IcecreamDelete
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
